# Configuration for Auction running Rand Greedy Algorithm

auction:
  bidders: 
    - name: 'ali'
      cls: 'comblearn.data.DSFValueFunction'
      args: [100, [2, 3, 2], 10]
    - name: 'hassan'
      cls: 'comblearn.data.DSFValueFunction'
      args: [100, [2, 3, 2], 10]
    - name: 'mahdi'
      cls: 'comblearn.data.DSFValueFunction'
      args: [100, [2, 3, 2], 10]

  
  items: [0, 1, 2, 3, 4, 5, 6, 7]

  data:
    q-init: 50
    q-max: 55
    brute-force: true

  query:
    marginal: False
    max-retries: 10

  device: 'cuda'


  learning:
    cls: 'comblearn.optim.learning.DSFLearner'
    optimizer: torch.optim.SGD
    learning-rate: 0.01
    epochs: 3000
    models:
      - name: 'ali'
        cls: 'comblearn.data.DSFValueFunction'
        args: [80, [10], 20]
      - name: 'hassan'
        cls: 'comblearn.data.DSFValueFunction'
        args: [80, [10], 20]
      - name: 'mahdi'
        cls: 'comblearn.data.DSFValueFunction'
        args: [80, [10], 20]

  allocation:
    scheme: 'RandGreedy'
    optimizer: 'comblearn.optim.RandGreedyOptimizer'
    delta: 0.005
    sample_rate: 5



