# Configuration for Auction running Rand Greedy Algorithm

auction:
  bidders: 
    - name: 'ali'
      cls: 'comblearn.data.DSFValueFunction'
      args: [100, [2, 3, 2], 500]
    - name: 'hassan'
      cls: 'comblearn.data.DSFValueFunction'
      args: [100, [2, 3, 2], 500]
    - name: 'mahdi'
      cls: 'comblearn.data.DSFValueFunction'
      args: [100, [2, 3, 2], 500]
    - name: 'arash'
      cls: 'comblearn.data.DSFValueFunction'
      args: [100, [2, 3, 2], 500]
    - name: 'mohammad'
      cls: 'comblearn.data.DSFValueFunction'
      args: [100, [2, 3, 2], 500]
  
  items: [0, 1, 2, 3, 4, 5, 6, 7, 8]

  data:
    q-init: 128
    q-max: 135
    brute-force: true

  query:
    marginal: False
    max-retries: 10

  device: 'cuda'


  learning:
    cls: 'comblearn.optim.learning.DSFLearner'
    optimizer: torch.optim.SGD
    learning-rate: 0.005
    epochs: 3000
    models:
      - name: 'ali'
        cls: 'comblearn.data.DSFValueFunction'
        args: [110, [3], 300]
      - name: 'hassan'
        cls: 'comblearn.data.DSFValueFunction'
        args: [110, [3], 300]
      - name: 'mahdi'
        cls: 'comblearn.data.DSFValueFunction'
        args: [110, [3], 300]
      - name: 'arash'
        cls: 'comblearn.data.DSFValueFunction'
        args: [110, [3], 300]
      - name: 'mohammad'
        cls: 'comblearn.data.DSFValueFunction'
        args: [110, [3], 300]

  allocation:
    scheme: 'RandGreedy'
    optimizer: 'comblearn.optim.RandGreedyOptimizer'
    delta: 0.005
    sample_rate: 5



