auction:
  bidders: 
    - name: '0'
      cls: 'comblearn.data.CoverageValueFunction'
      args: [1000, 0.2]
    - name: '1'
      cls: 'comblearn.data.CoverageValueFunction'
      args: [1000, 0.5]
    - name: '2'
      cls: 'comblearn.data.CoverageValueFunction'
      args: [1000, 0.8]


  
  items: [0, 1, 2, 3, 4, 5, 6, 7]

  data:
    q-init: 64
    q-max: 1028
    brute-force: True
    init: True

  query:
    marginal: False
    max-retries: 10

  device: 'cuda'

  queries_path: '/home/mahdi_mousavi/comb-auction/notebooks/lsvm_queries.txt'


  learning:
    cls: 'comblearn.optim.learning.DSFLearner'
    optimizer: torch.optim.Adam
    learning-rate: 0.01
    epochs: 10000

    comp: True

    models:
      - name: '0'
        cls: 'comblearn.data.ExtendedDSFValueFunction'
        args: [60, [64, 64, 64], 125]
      - name: '1'
        cls: 'comblearn.data.ExtendedDSFValueFunction'
        args: [60, [64, 64, 64], 125]
      - name: '2'
        cls: 'comblearn.data.ExtendedDSFValueFunction'
        args: [60, [64, 64, 64], 200]
    models1:
      - name: '0'
        cls: 'comblearn.data.DSFValueFunction'
        args: [60, [64, 64, 64], 95]
      - name: '1'
        cls: 'comblearn.data.DSFValueFunction'
        args: [60, [64, 64, 64], 95]
      - name: '2'
        cls: 'comblearn.data.DSFValueFunction'
        args: [60, [64, 64, 64], 150]


  allocation:
    scheme: 'RandGreedy'
    optimizer: 'comblearn.optim.RandGreedyOptimizer'
    delta: 0.005
    sample_rate: 5



