# Configuration for Auction running Rand Greedy Algorithm

auction:
  bidders: 
    - name: '0'
      cls: 'comblearn.data.DSFValueFunction'
      args: [60, [64, 128, 64], 60]
    - name: '1'
      cls: 'comblearn.data.DSFValueFunction'
      args: [60, [32, 64, 32], 30]
    - name: '2'
      cls: 'comblearn.data.DSFValueFunction'
      args: [60, [32, 128, 64], 40]


  
  items: [0, 1, 2, 3, 4, 5, 6, 7]

  data:
    q-init: 64
    q-max: 68
    brute-force: True
    init: True

  query:
    marginal: False
    max-retries: 10

  device: 'cuda'

  queries_path: '/home/mahdi_mousavi/comb-auction/notebooks/lsvm_queries.txt'


  learning:
    cls: 'comblearn.optim.learning.DSFLearner'
    optimizer: torch.optim.Adam
    learning-rate: 0.01
    epochs: 6000
    models:
      - name: '0'
        cls: 'comblearn.data.ExtendedDSFValueFunction'
        args: [60, [5, 5], 5]
      - name: '1'
        cls: 'comblearn.data.ExtendedDSFValueFunction'
        args: [60, [5, 5], 5]
      - name: '2'
        cls: 'comblearn.data.ExtendedDSFValueFunction'
        args: [60, [5, 5], 5]


  allocation:
    scheme: 'RandGreedy'
    optimizer: 'comblearn.optim.RandGreedyOptimizer'
    delta: 0.005
    sample_rate: 5



