# Configuration for Auction running Rand Greedy Algorithm

auction:
  bidders: 
    - name: 'ali'
      cls: 'comblearn.data.DSFValueFunction'
      args: [100, [2, 3, 2], 500]
    - name: 'hassan'
      cls: 'comblearn.data.DSFValueFunction'
      args: [100, [2, 3, 2], 500]
    - name: 'mahdi'
      cls: 'comblearn.data.DSFValueFunction'
      args: [100, [2, 3, 2], 500]
    - name: 'jafar'
      cls: 'comblearn.data.DSFValueFunction'
      args: [100, [2, 3, 2], 500]
    - name: 'arash'
      cls: 'comblearn.data.DSFValueFunction'
      args: [100, [2, 3, 2], 500]
  
  items: [0, 1, 2, 3, 4, 5, 6, 7]

  data:
    q-init: 500
    q-max: 510

  query:
    marginal: False
    max-retries: 10

  device: cuda


  learning:
    cls: 'comblearn.optim.learning.DSFLearner'
    optimizer: torch.optim.SGD
    learning-rate: 0.001
    epochs: 1000
    models:
      - name: 'ali'
        cls: 'comblearn.data.DSFValueFunction'
        args: [110, [2, 4], 300]
      - name: 'hassan'
        cls: 'comblearn.data.DSFValueFunction'
        args: [110, [2, 4], 300]
      - name: 'mahdi'
        cls: 'comblearn.data.DSFValueFunction'
        args: [110, [2, 4], 300]
      - name: 'jafar'
        cls: 'comblearn.data.DSFValueFunction'
        args: [110, [2, 4], 300]
      - name: 'arash'
        cls: 'comblearn.data.DSFValueFunction'
        args: [110, [2, 4], 300]

  allocation:
    scheme: 'GradientAscent'
    optimizer: 'comblearn.optim.GradientAscentOptimizer'
    learning-rate: 0.0002
    batch-size: 100
    eps: 0.001


